---
language: python
python:
  - "3.8"

services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash  # yamllint disable-line rule:line-length

install:
  - curl https://gist.githubusercontent.com/030/fa2454b56c525286b39d549583173d8e/raw/63e8546854b9986e416b80e083075016b27a3ed7/ansible-ci-requirements.sh | sudo bash  # yamllint disable-line rule:line-length

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
