---
services: docker

env:
  - distro: centos7

script:
  - chmod +x ./tests/geerlingguy.test/ansible-role-test.sh
  - ./tests/geerlingguy.test/ansible-role-test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
