---
- name: debian vars
  include_vars: Debian.yml
  when: ansible_os_family == 'Debian'

- name: redhat vars
  include_vars: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Download.
  get_url:
    url: "{{ firefox_url }}"
    dest: /tmp/firefox-{{ firefox_version }}.tar.bz2
    checksum: "{{ firefox_checksum }}"

- block:
    - name: remove the Firefox package
      package:
        name: firefox
        state: absent

    - name: Dependencies.
      package:
        name: "{{ item }}"
      with_items: "{{ firefox_dependencies }}"

    - name: Create directory.
      file:
        path: "{{ firefox_home }}"
        state: directory
        mode: 0755

    - name: Unarchive.
      unarchive:
        src: "{{ firefox_download }}"
        dest: "{{ firefox_home }}"
        remote_src: true
        creates: "{{ firefox_bin }}"

    - name: Symlink.
      file:
        src: "{{ firefox_bin }}"
        dest: /usr/bin/firefox
        state: link
  become: true

- block:
    - name: Create icons directory.
      file:
        path: "{{ firefox_desktop_icon_path }}"
        state: directory
        mode: 0755

    - name: Copy firefox logo.
      copy:
        src: "{{ firefox_logo }}"
        dest: "{{ firefox_desktop_icon_dest }}"
        remote_src: true

    - name: Create desktop icon.
      template:
        src: firefox.desktop.j2
        dest: /usr/share/applications/firefox.desktop
        owner: root
        group: root
        mode: 0644
  when: firefox_desktop_icon
