---
- name: Unzip.
  package:
    name: unzip

- name: Download.
  get_url:
    url: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
    dest: /tmp/firefox-latest.tar.bz2
    checksum: "{{ firefox_checksum }}"

- name: Unarchive.
  unarchive:
    src: /tmp/firefox-latest.tar.bz2
    dest: /usr/lib64
    remote_src: yes

- name: Create desktop icon.
  copy:
    src: firefox.desktop
    dest: /usr/share/applications/firefox.desktop
    owner: root
    group: root
    mode: 0644
  when: firefox_desktop_icon
