---
- import_tasks: get_version_from_api.yml
  when: firefox_get_version_from_api

- name: Download.
  get_url:
    url: "{{ firefox_url }}/{{ firefox_version }}/linux-x86_64/en-US/firefox-{{ firefox_version }}.tar.bz2"
    dest: /tmp/firefox-{{ firefox_version }}.tar.bz2
    checksum: "{{ firefox_checksum }}"

- block:
    - name: remove the Firefox package
      yum:
        name: firefox
        state: absent
    
    - name: Dependencies.
      package:
        name: "{{ item }}"
      with_items:
        - bzip2
        - gtk3
        - libXt

    - name: Create directory.
      file:
        path: "{{ firefox_home }}"
        state: directory
        mode: 0755
    
    - name: Unarchive.
      unarchive:
        src: "{{ firefox_download }}"
        dest: "{{ firefox_home }}"
        remote_src: yes
        creates: "{{ firefox_bin }}"

    - name: Symlink.
      file:
        src: "{{ firefox_bin }}"
        dest: /usr/bin/firefox
        state: link
      notify:
        - Check version.
  become: true

- block:
    - name: Create icons directory.
      file:
        path: "{{ firefox_desktop_icon_path }}"
        state: directory
        mode: 0755

    - name: Copy firefox logo.
      copy:
        src: "{{ firefox_home }}/firefox/browser/chrome/icons/default/default128.png"
        dest: "{{ firefox_desktop_icon_dest }}"
        remote_src: yes
 
    - name: Create desktop icon.
      template:
        src: firefox.desktop.j2
        dest: /usr/share/applications/firefox.desktop
        owner: root
        group: root
        mode: 0644
  when: firefox_desktop_icon
