---
- name: Download.
  get_url:
    url: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
    dest: /tmp/firefox-latest
    checksum: {{ firefox_checksum }}

- name: Create desktop icon.
  copy:
    src: firefox.desktop
    dest: /usr/share/applications/firefox.desktop
    owner: root
    group: root
    mode: 0644
  when: firefox_desktop_icon
